logging:
  file: logs/doyle_buchwald_hartwig_mlp.log
  level: INFO
output:
  model_path: models/doyle_buchwald_hartwig_mlp_model.pkl
  predictions_path: results/
  report_format: json
  save_model: true
pipeline:
  steps:
    data_loading:
      feature_columns:
      - Ligand
      - Additive
      - Base
      - Aryl_halide
      file_type: csv
      missing_value_strategy: drop
      target_column: Output
    evaluation:
      feature_importance: false
      metrics:
        regression:
        - rmse
        - mae
        - r2
      shap_analysis: false
    feature_encoding:
      Additive:
        encoder: morgan_fingerprint
        params:
          chiral: true
          n_bits: 1024
          radius: 2
      Aryl_halide:
        encoder: morgan_fingerprint
        params:
          chiral: true
          n_bits: 1024
          radius: 2
      Base:
        encoder: morgan_fingerprint
        params:
          chiral: true
          n_bits: 1024
          radius: 2
      Ligand:
        encoder: morgan_fingerprint
        params:
          chiral: true
          n_bits: 2048
          radius: 2
    model_training:
      cv:
        method: kfold
        n_splits: 5
        random_state: 42
        shuffle: true
      device: cpu
      params:
        activation: relu
        alpha: 0.0001
        batch_size: auto
        early_stopping: true
        hidden_layer_sizes:
        - 1024
        - 512
        - 256
        - 128
        learning_rate: adaptive
        learning_rate_init: 0.001
        max_iter: 1000
        n_iter_no_change: 10
        random_state: 42
        solver: adam
        validation_fraction: 0.1
        verbose: true
      task_type: regression
      type: mlp
