name: reaction_yield_prediction
data_path: data/reaction_data.csv
feature_configs:
  reactant_a:
    type: fingerprint
    params:
      radius: 2
      n_bits: 2048
  temperature:
    type: numerical
    params:
      normalize: true
model_config:
  type: mlp
  hidden_dims: [512, 256]
  dropout: 0.1
training_config:
  batch_size: 32
  max_epochs: 100
  learning_rate: 0.001
output_dir: outputs
seed: 42 